name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller (Linux/macOS)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          DATE=$(date +'%Y-%m-%d')
          COMMIT_HASH=$(git rev-parse --short HEAD)

          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            OS_NAME="linux"
          else
            OS_NAME="macos"
          fi

          EXECUTABLE_NAME="${OS_NAME}_rpc-bridge_${DATE}-${COMMIT_HASH}"
          echo "Building executable with name: $EXECUTABLE_NAME"

          pyinstaller \
            --onefile \
            --name $EXECUTABLE_NAME \
            --hidden-import=jinja2.runtime \
            --hidden-import=markdown_checklist.extension \
            --add-data="templates/*:templates/" \
            --add-data="static/*:static/" \
            --add-data="static/img/*:static/img/" \
            --add-data="static/img/discord_avatars/*:static/img/discord_avatars" \
            --add-data="static/js/*:static/js" \
            --add-data="doc_images/*:doc_images/" \
            --add-data="README.md:." \
            rpc_bridge_server.py

      - name: Build with PyInstaller (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          $DATE = Get-Date -Format "yyyy-MM-dd-HHmm"
          $COMMIT_HASH = (git rev-parse --short HEAD)
          $EXECUTABLE_NAME = "windows_rpc-bridge_$DATE-$COMMIT_HASH.exe"
          Write-Host "Building executable with name: $EXECUTABLE_NAME"

          pyinstaller --onefile `
            --name $EXECUTABLE_NAME `
            --hidden-import=jinja2.runtime `
            --hidden-import=markdown_checklist.extension `
            --add-data="templates/*;templates/" `
            --add-data="static/*;static/" `
            --add-data="static/img/*;static/img/" `
            --add-data="static/img/discord_avatars/*;static/img/discord_avatars" `
            --add-data="static/js/*;static/js" `
            --add-data="doc_images/*;doc_images/" `
            --add-data="README.md;." `
            rpc_bridge_server.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: executable-windows-latest
          path: ./windows/

      - name: Download all artifacts (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: executable-ubuntu-latest
          path: ./ubuntu/

      - name: Download all artifacts (MacOS)
        uses: actions/download-artifact@v4
        with:
          name: executable-macos-latest
          path: ./macos/

      - name: Create Tag
        id: tag_version
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ubuntu/linux_*
            windows/windows_*.exe
            macos/macos_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
